name: rippled

on:
  schedule:
    - cron: '0 6 * * *' # Every day at 6:00 AM UTC.

jobs:
  call-build-rippled-workflow:
    uses: runziggurat/xrpl/.github/workflows/build-rippled.yml@main

  call-build-ziggurat-workflow:
    uses: runziggurat/zcash/.github/workflows/build-ziggurat.yml@main
    with:
      extra-args: --features performance

  test-rippled:
    runs-on: ubuntu-latest
    needs: [ call-build-ziggurat-workflow, call-build-rippled-workflow ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: rustup toolchain install stable --profile minimal
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - uses: actions/download-artifact@v3
        with:
          name: rippled-executable
          path: ./rippled
      - uses: actions/download-artifact@v3
        with:
          name: ziggurat-executable
          path: ./ziggurat
      - name: Enable openSSL legacy functions
        run: |
          cp /etc/ssl/openssl.cnf ./
          sed -i 's/^\#openssl_conf = openssl_init/openssl_conf = openssl_init/' openssl.cnf
          sed -i '/^\default = default_sect/a legacy = legacy_sect' openssl.cnf
          sed -i '/^\[default_sect\]/a activate = 1' openssl.cnf
          echo "[legacy_sect]" >> openssl.cnf
          echo "activate = 1" >> openssl.cnf
      - name: Run setup script
        env:
          OPENSSL_CONF: /home/runner/work/xrpl/xrpl/openssl.cnf
          RIPPLED_BIN_PATH: /home/runner/work/xrpl/xrpl/rippled
        run: |
          pip3 install xrpl-py
          chmod +x rippled/rippled
          ./tools/setup_env.sh
      - name: Prepare IP addresses
        run: sudo python3 ./tools/ips.py --subnet 1.1.1.0/24 --file src/tools/ips.rs --dev lo
      - name: Run ziggurat suite
        continue-on-error: true
        run: |
          rm ./ziggurat/*.d
          mv ./ziggurat/ziggurat_* ziggurat_test
          chmod +x ziggurat_test
          mkdir -p results/rippled
          mv results/rippled/latest.jsonl results/rippled/previous.jsonl
          ./ziggurat_test --test-threads=1 --nocapture -Z unstable-options --report-time --format json > results/rippled/latest.jsonl
      - uses: actions/upload-artifact@v3
        with:
          name: latest-result
          path: results/rippled/latest.jsonl
      - uses: actions/upload-artifact@v3
        with:
          name: previous-result
          path: results/rippled/previous.jsonl

  call-process-results-workflow:
    needs: [ test-rippled ]
    uses: runziggurat/zcash/.github/workflows/process-results.yml@main
    with:
      name: rippled

  call-diff-with-previous-workflow:
    needs: [ test-rippled ]
    uses: runziggurat/zcash/.github/workflows/diff-with-previous.yml@main
